### ISSUE TITLE
Bug with the sockets and real time statistics

### ISSUE THREAD

**Issue by EylonSho** [TechnionYearlyProject/SummitBTW#112]
@tomerkay, when I'm running the script `simulate.py` as the main script, although the simulation is working -  I am getting the following error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/EylonSho/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/EylonSho/Documents/workspace/SummitBTW/statistics/realtime.py", line 19, in run
    self.sock.bind(("0.0.0.0", 1482))
OSError: [Errno 48] Address already in use
```

**Comment by tomerkay** [comment]
fixed.
